services:
  mysql:
    image: mysql:5.7
    container_name: mysql-db
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
    ports:
      - 3306:3306
    volumes:
      - ./mysql_data:/var/lib/mysql
  
volumes:
  mysql_data: